[build]
  publish = "."

[[redirects]]
  from = "/api/counter/:page"
  to = "https://api.counterapi.dev/v1/pathway-strex/:page/up"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
